export const constants = {
        SARGASSUM_POTENTIAL: 37_500_000, // TOTAL DEL MERCADO DE SARGAZO KG
        ALGINATE_PERCENTAGE_PRODUCTION: 16, //PORCENTAJE DE PRODUCCION DE ALGINATO RELATIVO AL PROCESADO 
        CELULOSE_PERCENTAGE_PRODUCTION: 24,//PORCENTAJE DE PRODUCCION DE CELULOSA RELATIVO AL PROCESADO
        SOLID_FOAM_PERCENTAGE_RELATIVE_TO_ALGINATE: 1, // PORCENTAJE DE PRODUCCION DE SOLID FOAM RELATIVO AL ALGINATO
        ALGINATE_TO_SOLIDFOAM_RATIO_NO_SOLUBLE: 1/0.19,
        ALGINATE_TO_SOLIDFOAM_RATIO_SOLUBLE: 1/0.19,
        CELULOSE_TO_SOLIDFOAM_RATIO_NO_SOLUBLE: 1/0.8,
        CELULOSE_TO_SOLIDFOAM_RATIO_SOLUBLE: 1/0.8,
        MAX_TEORICAL_PROCESSED: {"2 ton": 2000*0.12*600,"6 ton": 6000*0.12*600}
    }
    
